# Generated by Django 5.0.6 on 2024-11-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganisationManager', '0012_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='brnch_mstr',
            name='branc_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
