# Generated by Django 5.0.6 on 2024-12-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0118_alter_emp_master_emp_gender_and_more'),
        ('OrganisationManager', '0014_companypolicy_specific_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset (e.g., Laptop, Phone, etc.)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details about the asset', null=True)),
                ('total_quantity', models.PositiveIntegerField(help_text='Total number of assets available')),
                ('available_quantity', models.PositiveIntegerField(help_text='Number of assets currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='OrganisationManager.assetmaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transactions', to='EmpManagement.emp_master')),
            ],
        ),
    ]
