# Generated by Django 5.0.6 on 2024-11-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cntry_mstr',
            name='timezone',
            field=models.CharField(help_text="Set timezone as per IANA timezone database format, e.g., 'America/New_York'", max_length=100, null=True),
        ),
    ]
