# Generated by Django 5.0.6 on 2024-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docexpemailtemplate',
            name='template_name',
            field=models.CharField(choices=[('Employee Notification', 'Employee Notification'), ('ESS User Notification', 'ESS User Notification')], max_length=100),
        ),
    ]
