# Generated by Django 5.0.6 on 2024-12-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0116_rename_emp_active_date_emp_master_emp_date_of_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_master',
            name='emp_reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master'),
        ),
    ]
