# Generated by Django 5.0.6 on 2024-12-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0117_emp_master_emp_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('divorced', 'divorced'), ('widow', 'widow')], max_length=10, null=True),
        ),
    ]
