# Generated by Django 5.0.6 on 2024-11-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0042_leaveapprovallevels_is_compensatory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatoryleaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='compensatoryleaverequest',
            name='approved_on',
        ),
    ]
