# Generated by Django 5.0.6 on 2024-11-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0043_remove_compensatoryleaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproval',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='LeaveManagement.employee_leave_request'),
        ),
    ]
