# Generated by Django 5.0.6 on 2024-11-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0046_compensatoryleaverequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproval',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
