# Generated by Django 5.0.6 on 2024-11-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0048_leaveapproval_end_date_leaveapproval_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapproval',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaveapproval',
            name='start_date',
        ),
    ]
