# Generated by Django 5.0.6 on 2024-11-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_users'),
        ('LeaveManagement', '0049_remove_leaveapproval_end_date_and_more'),
        ('OrganisationManager', '0013_brnch_mstr_branc_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='friday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='monday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='role',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='saturday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='sunday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='thursday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='tuesday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='wednesday_shift',
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='rotation_cycle_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='department',
        ),
        migrations.AlterField(
            model_name='weeklyshiftschedule',
            name='employee',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
        migrations.CreateModel(
            name='WeeklyShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_friday', to='LeaveManagement.shift')),
                ('monday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_monday', to='LeaveManagement.shift')),
                ('saturday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_saturday', to='LeaveManagement.shift')),
                ('sunday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_sunday', to='LeaveManagement.shift')),
                ('thursday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_thursday', to='LeaveManagement.shift')),
                ('tuesday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_tuesday', to='LeaveManagement.shift')),
                ('wednesday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_wednesday', to='LeaveManagement.shift')),
            ],
        ),
        migrations.CreateModel(
            name='RotationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.weeklyshiftschedule')),
                ('weekly_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.weeklyshiftpattern')),
            ],
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='weekly_patterns',
            field=models.ManyToManyField(blank=True, through='LeaveManagement.RotationPattern', to='LeaveManagement.weeklyshiftpattern'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.dept_master'),
        ),
    ]
