# Generated by Django 5.0.6 on 2024-11-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_users'),
        ('LeaveManagement', '0051_remove_weeklyshiftschedule_weekly_patterns_and_more'),
        ('OrganisationManager', '0013_brnch_mstr_branc_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='friday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='monday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='role',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='rotation_pattern',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='saturday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='sunday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='thursday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='tuesday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='wednesday_shift',
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='weekly_patterns',
            field=models.ManyToManyField(blank=True, through='LeaveManagement.RotationPattern', to='LeaveManagement.weeklyshiftpattern'),
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='department',
        ),
        migrations.AlterField(
            model_name='weeklyshiftschedule',
            name='employee',
            field=models.ManyToManyField(blank=True, to='EmpManagement.emp_master'),
        ),
        migrations.AlterField(
            model_name='weeklyshiftschedule',
            name='rotation_cycle_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.brnch_mstr'),
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrganisationManager.dept_master'),
        ),
    ]
