# Generated by Django 5.0.6 on 2024-11-18 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0052_remove_weeklyshiftschedule_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='department',
        ),
        migrations.AddField(
            model_name='weeklyshiftschedule',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
