# Generated by Django 5.0.6 on 2024-11-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0054_weeklyshiftschedule_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='weekly_patterns',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='friday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='monday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='saturday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='sunday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='thursday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='tuesday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftpattern',
            name='wednesday_shift',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='weeklyshiftschedule',
            name='employee',
        ),
        migrations.DeleteModel(
            name='RotationPattern',
        ),
        migrations.DeleteModel(
            name='WeeklyShiftPattern',
        ),
        migrations.DeleteModel(
            name='WeeklyShiftSchedule',
        ),
    ]
