# Generated by Django 5.0.6 on 2024-11-18 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_users'),
        ('LeaveManagement', '0055_remove_weeklyshiftschedule_weekly_patterns_and_more'),
        ('OrganisationManager', '0013_brnch_mstr_branc_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation_cycle_weeks', models.IntegerField(default=4)),
                ('friday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_friday', to='LeaveManagement.shift')),
                ('monday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_monday', to='LeaveManagement.shift')),
                ('saturday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_saturday', to='LeaveManagement.shift')),
                ('sunday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_sunday', to='LeaveManagement.shift')),
                ('thursday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_thursday', to='LeaveManagement.shift')),
                ('tuesday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_tuesday', to='LeaveManagement.shift')),
                ('wednesday_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_wednesday', to='LeaveManagement.shift')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('departments', models.ManyToManyField(blank=True, to='OrganisationManager.dept_master')),
                ('employees', models.ManyToManyField(blank=True, to='EmpManagement.emp_master')),
                ('shift_patterns', models.ManyToManyField(blank=True, to='LeaveManagement.shiftpattern')),
            ],
        ),
    ]
