# Generated by Django 5.0.6 on 2024-11-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0056_shiftpattern_employeeshiftschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeshiftschedule',
            old_name='employees',
            new_name='employee',
        ),
    ]
