# Generated by Django 5.0.6 on 2024-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0057_rename_employees_employeeshiftschedule_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeshiftschedule',
            old_name='shift_patterns',
            new_name='week_patterns',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='rotation_cycle_weeks',
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='rotation_cycle_weeks',
            field=models.IntegerField(default=4),
        ),
    ]
