# Generated by Django 5.0.6 on 2024-11-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpManagement', '0114_alter_emp_master_users'),
        ('LeaveManagement', '0058_rename_shift_patterns_employeeshiftschedule_week_patterns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpManagement.emp_master')),
                ('override_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeaveManagement.shift')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
