# Generated by Django 5.0.6 on 2024-11-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0059_shiftoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshiftschedule',
            name='week_patterns',
        ),
        migrations.CreateModel(
            name='WeekPatternAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveManagement.employeeshiftschedule')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeaveManagement.shiftpattern')),
            ],
            options={
                'unique_together': {('schedule', 'week_number')},
            },
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='pattern_templates',
            field=models.ManyToManyField(blank=True, through='LeaveManagement.WeekPatternAssignment', to='LeaveManagement.shiftpattern'),
        ),
    ]
