# Generated by Django 5.0.6 on 2024-11-19 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0060_remove_employeeshiftschedule_week_patterns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeshiftschedule',
            old_name='pattern_templates',
            new_name='week_patterns',
        ),
    ]
