# Generated by Django 5.0.6 on 2024-11-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0061_rename_pattern_templates_employeeshiftschedule_week_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='is_rotating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='single_shift_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_shift_schedules', to='LeaveManagement.shiftpattern'),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='week_patterns',
            field=models.ManyToManyField(blank=True, related_name='week_pattern_schedules', through='LeaveManagement.WeekPatternAssignment', to='LeaveManagement.shiftpattern'),
        ),
    ]
