# Generated by Django 5.0.6 on 2024-11-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0062_employeeshiftschedule_is_rotating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshiftschedule',
            name='start_date',
        ),
    ]
