# Generated by Django 5.0.6 on 2024-11-21 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0063_remove_employeeshiftschedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
