# Generated by Django 5.0.6 on 2024-12-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0066_alter_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRejoining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejoining_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejoining_details', to='LeaveManagement.employee_leave_request')),
            ],
        ),
    ]
