# Generated by Django 5.0.6 on 2024-12-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0067_employeerejoining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeRejoining',
        ),
    ]
