# Generated by Django 5.0.6 on 2024-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0069_employeerejoining'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerejoining',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
    ]
