# Generated by Django 5.0.6 on 2024-12-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0070_employeerejoining_paid_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerejoining',
            name='paid_leave_days',
        ),
    ]
